default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bhangaar_development

test:
  <<: *default
  database: bhangaar_test


production:
  <<: *default
  database: bhangaar_production
  username: bhangaar
  password: <%= ENV['BHANGAAR_DATABASE_PASSWORD'] %>
